feat(api): identify gitlab instances by hostname
immobiliare/backstage-plugin-gitlab pull request #127
Opened 2023-03-07 10:45 UTC by manuelstein

## 🚨 Proposed changes

closes #118 
- processor and router have been changed to identify a GitLab instance by its hostname rather than a generated index number.
- refactored the processor conditional logic to decide if the entity needs to be processed (avoid looking up the host on entities that are excluded by their kind)
- tests have been updated

## ⚙️ Types of changes

What types of changes does your code introduce? _Put an `x` in the boxes that apply_

-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Bugfix (non-breaking change which fixes an issue)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] Documentation Update (if none of the other choices apply)
-   [ ] Refactor

2023-03-08 11:12 UTC, antoniomuso requested changes
LGTM! Great work. Only some things.

- You have to change in frontend plugin for all cards:
```diff
- .build(gitlab_instance || '0')
+ .build(gitlab_instance || 'gitlab.com')

2023-03-08 11:12 UTC, antoniomuso commented on packages/gitlab-backend/src/processor/processor.ts
> +        let url: URL;
Here we have to do the check of location type, it must be `url` otherwise, we should skip.

2023-03-08 11:44 UTC, manuelstein commented on packages/gitlab-backend/src/processor/processor.ts
> +        let url: URL;
We're using a GitLab entity provider that generates entities with location type `gitlab`, the format is a GitLab API URL and I'd still want the instance (host) to be derived from the URL. As long as the target parses as a URL and it has an integration config, it should be good to be used for an instance.

2023-03-08 11:45 UTC, manuelstein commented
> LGTM! Great work. Only some things.
> 
> * You have to change in frontend plugin for all cards:
> 
> ```diff
> - .build(gitlab_instance || '0')
> + .build(gitlab_instance || 'gitlab.com')
> ```

yes, reintroducing the change :)
I'll also squash-commit.
Is it correct to assume that this is a feature (not a breaking change)?

2023-03-08 12:02 UTC, antoniomuso commented
> yes, reintroducing the change :) I'll also squash-commit. Is it correct to assume that this is a feature (not a breaking change)?

This is a breaking change because the annotations can be set manually.

2023-03-08 12:03 UTC, antoniomuso commented
Can you also update the documentation ?

2023-03-08 12:07 UTC, antoniomuso commented on packages/gitlab-backend/src/processor/processor.ts
> +        let url: URL;
Okay I understand the problem; Okay, for now, we can avoid checking the type.

2023-03-08 12:52 UTC, antoniomuso commented
> sure, I'm having trouble finding related documentation. Could you pls point me to it?

I refer to the annotation section, https://github.com/immobiliare/backstage-plugin-gitlab/blob/main/README.md#annotations, now target annotation has more meaning, we can add it; if someone wants to force a particular gitlab instance.

2023-03-08 15:58 UTC, antoniomuso commented
> > sure, I'm having trouble finding related documentation. Could you pls point me to it?
> 
> I refer to the annotation section, https://github.com/immobiliare/backstage-plugin-gitlab/blob/main/README.md#annotations, now target annotation has more meaning, we can add it; if someone wants to force a particular gitlab instance.

Rethinking more. For now, it is better to avoid adding it. If I change idea, I will add it by myself.

2023-03-08 16:02 UTC, antoniomuso approved these changes
LGTM! Thank you! You did a really good job. :rocket:

2023-03-08 16:02 UTC, merged

2023-03-09 11:25 UTC, antoniomuso commented
hey @manuelstein, yours featues are up [v5.0.0](https://github.com/immobiliare/backstage-plugin-gitlab/releases/tag/v5.0.0)

2023-03-09 22:44 UTC, manuelstein commented
Wow, thank you, that's awesome!