fix: identify instance by host and documentation
immobiliare/backstage-plugin-gitlab pull request #155
Opened 2023-03-28 09:39 UTC by manuelstein

closes #154

## 🚨 Proposed changes

fixes incomplete changes to identify GitLab instances.
adds documentation

## ⚙️ Types of changes

What types of changes does your code introduce? _Put an `x` in the boxes that apply_

-   [ ] New feature (non-breaking change which adds functionality)
-   [X] Bugfix (non-breaking change which fixes an issue)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [X] Documentation Update (if none of the other choices apply)
-   [ ] Refactor

2023-03-28 14:14 UTC, antoniomuso requested changes
Hi @manuelstein, Thank you for the PR. I prefer not to specify the `instance` annotation in the documentation because the processor automatically generates this annotation.

2023-03-28 14:14 UTC, antoniomuso commented on README.md
> +By default, the plugin automatically shows the project info corresponding to the location of the `catalog.yaml` file. But you could need some time to force another project. The GitLab instance defaul
I think it is better not to add the annotation `gitlab.com/instance` in the documentation.

2023-03-28 14:14 UTC, antoniomuso commented on README.md
> +        gitlab.com/instance: 'hostname' # defaults to 'gitlab.com'
As said in the previous comment.

2023-05-08 10:24 UTC, closed without merging

2023-05-09 09:24 UTC, manuelstein commented
I see you've fixed the IssuesTable and MergeRequestsTable from this PR 3 weeks ago, which is the crucial part.
Thx, Manuel