feat(added-secure-prop-to-proxy-config) - added new parameter "secure…
immobiliare/backstage-plugin-gitlab pull request #217
Opened 2023-05-22 10:37 UTC by goququ

…" to be able to handle

handle "UNABLE_TO_VERIFY_LEAF_SIGNATURE" error

## 🚨 Proposed changes

> Please review the [guidelines for contributing](../../CONTRIBUTING.md) to this repository.

Hi, team! I am trying to use this plugin on my project and I have faced with some trouble to make it work with our instance of gitlab. So in general I want to be able to configure `secure` parameter according [this comment](https://github.com/chimurai/http-proxy-middleware/issues/233#issuecomment-355830567)

## ⚙️ Types of changes

What types of changes does your code introduce? _Put an `x` in the boxes that apply_

-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Bugfix (non-breaking change which fixes an issue)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] Documentation Update (if none of the other choices apply)
-   [ ] Refactor

2023-05-22 13:57 UTC, antoniomuso requested changes

2023-05-22 13:57 UTC, antoniomuso commented on packages/gitlab-backend/src/service/router.ts
> +        secure = process.env.NODE_TLS_REJECT_UNAUTHORIZED !== '0',
This parameter should be added to the configuration. In this way you can get it in this way: 
```ts
config.getOptionalBoolean('gitlab.proxySecure');
```

2023-05-23 08:33 UTC, antoniomuso requested changes
To use `config.getOptionalBoolean('gitlab.proxySecure')` you have to add the parameter in the [config.d.ts](https://github.com/immobiliare/backstage-plugin-gitlab/blob/main/packages/gitlab-backend/config.d.ts)

2023-05-23 08:33 UTC, antoniomuso commented on packages/gitlab-backend/src/service/router.ts
> +        process.env.NODE_TLS_REJECT_UNAUTHORIZED !== '0';
Please, don't use env variables. If someone wants this behavior, he can do it in the `app-config.yaml`.

2023-05-26 07:48 UTC, goququ commented
@antoniomuso hi, everything ok? Or I can do something else?

2023-05-26 08:51 UTC, antoniomuso commented
LGTM! But the type checking fails...

2023-05-26 14:04 UTC, goququ commented
> LGTM! But the type checking fails...

I haven‘t touched any react code. Do you think problem in my changes?

2023-05-26 14:25 UTC, antoniomuso approved these changes

2023-05-26 14:25 UTC, merged

2023-05-30 08:17 UTC, antoniomuso commented
hi @goququ, this MR in up with [v5.2.0](https://github.com/immobiliare/backstage-plugin-gitlab/releases/tag/v5.2.0). Thanks for your contribution :smile: