feat(readme): :sparkles: adds partial support for GLFM
immobiliare/backstage-plugin-gitlab pull request #499
Opened 2024-07-09 18:05 UTC by JWWilks

## 🚨 Proposed changes

The backstage MarkdownContent component only provides support for `gfm` (Git**Hub** Flavoured Markdown) and `common markdown`. This is because the underlying package ReactMarkdown, which uses [Remark](https://github.com/remarkjs/remark), can only support existing Remark plugins.

Remark does not have full support for Git**Lab** Flavoured Markdown, but there are some plugins which provide a few of the same features. This PR adds `toc` and `gemoji`, which will work with the GitLab variant.

## ⚙️ Types of changes

What types of changes does your code introduce? _Put an `x` in the boxes that apply_

-   [X] New feature (non-breaking change which adds functionality)
-   [ ] Bugfix (non-breaking change which fixes an issue)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] Documentation Update (if none of the other choices apply)
-   [ ] Refactor

## Extra considerations

GLFM expects TOCs in one of the following formats:
<table>
<tr><td><pre>
[TOC]
## My Header
### My Header 2
</pre></td><td>
<pre>
[[_TOC_]]
## My Header
### My Header 2</pre></td></tr></table>

But the remark-toc plugin requires that the TOC keyword be inside a header, like this:
```md
## Contents
## My Header
### My Header 2
```

To account for this, I added an extra util function which parses the readme and replaces `[TOC]` and `[[_TOC_]]` with `## Contents#`. This does unfortunately mean that the readme will have a "Contents" header which won't be exactly consistent with GitLab.

2024-07-09 18:07 UTC, JWWilks commented
Oh, I also added an `endOfLine: auto` to the prettier config because it was very mad at me about files I didn't change:
![image](https://github.com/immobiliare/backstage-plugin-gitlab/assets/75726489/7a0729c9-7f75-4211-b2ee-ed75675fcf9e)

2024-07-10 08:48 UTC, antoniomuso commented on packages/gitlab/src/components/widgets/ReadmeCard/ReadmeCard.tsx
> +    // // https://github.com/backstage/backstage/blob/master/packages/core-components/src/components/MarkdownContent/MarkdownContent.tsx#L28
```suggestion
    // https://github.com/backstage/backstage/blob/master/packages/core-components/src/components/MarkdownContent/MarkdownContent.tsx#L28
```

2024-07-10 09:34 UTC, antoniomuso requested changes
Hi @JWWilks, very nice work. My only doubt is when a header named `# Content` is in the Readme body.  We can try to fix it by adding in `parseGitLabReadme` function an invisible character at the end of `## Contents` ex: `## Cotentes${invisibleCharacter}`. I don't know if this can fix it but we could try it.

2024-07-12 07:41 UTC, antoniomuso approved these changes
Great job! Awesome solution! If you could fix the conventional commit issue, I merge it.

2024-07-17 07:23 UTC, antoniomuso approved these changes
I apologize for late approval. I have been sick these days. Great work; thank you so much. Excellent job!

2024-07-17 07:24 UTC, merged